### ISSUE TITLE
Extension is installed but no system config options

### ISSUE THREAD

**Issue by pushonrobert** [gordonknoppe/magento-cachebuster#7]
I have dropped in the extension files.

Extension is showing as installed under system > advanced.

However there is no options available within system config.

Magento ver. Enterprise 1.14.1.0

Any ideas why this is?

**Comment by gordonknoppe** [comment]
Hi @pushonrobert, I cannot reproduce this issue. On a clean install I see the configuration values in "System > Config" under "Advanced / System / Cachebuster Settings".

**Comment by gordonknoppe** [comment]
Please re-open with more details if you still have an issue.
