### ISSUE TITLE
Question regarding the regeneration of the timestamp

### ISSUE THREAD

**Issue by leiluspocus** [gordonknoppe/magento-cachebuster#9]
Hi,

I would like to use your module which seems to answer perfectly to my needs. 

However, I have a question regarding the regeneration of the timestamp. I would like my assets' URLs to be regenerated as soon as they have been modified. 

However, I notice than when I flush my cache, the timestamps are not regenerated. 

Hence my question: I'm not sure to understand in the module's logic when are the URLs timestamps regenerated ? 

Thank you in advance

**Comment by gordonknoppe** [comment]
Hello @leiluspocus, the way the extension works is to put the timestamps of each file into the URL rendered by Magento.  The timestamps are unique to each file so if you change one file then only that URL will change and the timestamps for everything else will remain the same.  Please check again and re-open this issue if you do not see it working.

**Comment by leiluspocus** [comment]
Hey @gordonknoppe  thank you for the quick answer ! 

Yes, the timestamps work. Example : 
- it's added on my styles.css file --> 
http://my.dev/skin/frontend/enterprise/my_company/css/styles.1470341520.css

I'm happy with that. However, I would like it to change everytime I flush the cache. But the timestamp stays like that : 
- http://my.dev/skin/frontend/enterprise/my_company/css/styles.1470341520.css

Hence the question : What makes the timestamp to be regenerate again ? It doesn't seem like you're caching it in the module, timestamps should regenerate everytime I flush the Javascript / CSS cache ? 

I'm using EE 1.13.1 by the way.

**Comment by leiluspocus** [comment]
Oh I didn't notice the method filemtime... Everytime an asset file is modified, the timestamp should be regenerated ? 
Thanks

**Comment by gordonknoppe** [comment]
Correct, the timestamp should only change when the file has been updated.  This is why the extension exists.. to take advantage of HTTP caching for static assets.

**Comment by leiluspocus** [comment]
Yes, my bad, I didn't pay attention to the filemtime function ...

Thank you very much and keep up the great job !

Laïla Atrmouh
819-580-4087
